### PR TITLE
cpp code suggestions

### PR DESCRIPTION
**Pull request by janoPig**
My code suggestions. They need to be properly tested.

### CODE REVIEW

**Comment by janoPig** [comment]
not work on linux

**Comment by kartelj** [comment]
Thanks, I will look onto linux soon. Can you point out the specifics regarding linux installation failure.

**Review by kartelj — COMMENTED** [review]
Everything seems nice.

**Comment by janoPig** [comment]
Hi, possible fix is in branch https://github.com/janoPig/rils-rols/tree/eigen-included

**Comment by janoPig** [comment]
I also add repo https://github.com/janoPig/RunSRBench to run SRBench for free with github actions for 4 configurations from 1 second to 5 minutes per fit task. With included eigen source run sucessful also RILS-ROLS

**Pull request closed without merging**
